/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grosirkosmetik;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafiadji
 */
public class LapTransaksi extends javax.swing.JFrame {

    Koneksi conn;
    DefaultTableModel TableLap;
    /**
     * Creates new form LapTransaksi
     */
    public LapTransaksi() {
        initComponents();
        conn = new Koneksi();
        loadTable(null);
    }
    
    public void loadTable(String waktu){
        Object[] field = {"Id Transaksi","Produk","Total Penjualan"};
        TableLap = new DefaultTableModel(null, field);
        TableLaporan.setModel(TableLap);
        
        try{
            ResultSet tlap = null;
            if(waktu == null){
                tlap = conn.select("SELECT ID_TRANS, PRODUK, SUM(TOTAL) as STOTAL FROM view_trans GROUP BY ID_TRANS");
            }
            else if(waktu == "hari"){
                tlap = conn.select("SELECT ID_TRANS, PRODUK, SUM(TOTAL) as STOTAL FROM view_trans WHERE DAY(TANGGAL_TRANS) = DAY(NOW()) GROUP BY PRODUK");
            }
            else if(waktu == "bulan"){
                tlap = conn.select("SELECT ID_TRANS, PRODUK, SUM(TOTAL) as STOTAL FROM view_trans WHERE MONTH(TANGGAL_TRANS) = MONTH(NOW()) GROUP BY PRODUK");
            }
            else if(waktu == "tahun"){
                tlap = conn.select("SELECT ID_TRANS, PRODUK, SUM(TOTAL) as STOTAL FROM view_trans WHERE YEAR(TANGGAL_TRANS) = YEAR(NOW()) GROUP BY PRODUK");
            }
            while(tlap.next()){
                String id_trans = tlap.getString("ID_TRANS");
                String prod = tlap.getString("PRODUK");
                String totjual = tlap.getString("STOTAL");
                String[] data = {id_trans, prod, totjual};
                TableLap.addRow(data);
            }
        }
        catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LJudul = new javax.swing.JLabel();
        Lpilih = new javax.swing.JLabel();
        CBWaktu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableLaporan = new javax.swing.JTable();
        BKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laporan Transaksi");

        LJudul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LJudul.setText("Laporan Transaksi");

        Lpilih.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lpilih.setText("Waktu Laporan");

        CBWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Waktu", "Harian", "Bulanan", "Tahunan" }));
        CBWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBWaktuActionPerformed(evt);
            }
        });

        TableLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableLaporan);

        BKembali.setText("Kembali");
        BKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJudul)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lpilih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BKembali)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lpilih)
                    .addComponent(CBWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBWaktuActionPerformed
        if(CBWaktu.getSelectedItem() == "Harian"){
            loadTable("hari");
        }
        else if(CBWaktu.getSelectedItem() == "Bulanan"){
            loadTable("bulan");
        }
        else if(CBWaktu.getSelectedItem() == "Tahunan"){
            loadTable("tahun");
        }
        else{
            loadTable(null);
        }
    }//GEN-LAST:event_CBWaktuActionPerformed

    private void BKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKembaliActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        mn.setLocationRelativeTo(null);
        mn.setDefaultCloseOperation(Login.DO_NOTHING_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LapTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKembali;
    private javax.swing.JComboBox<String> CBWaktu;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel Lpilih;
    private javax.swing.JTable TableLaporan;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
