/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grosirkosmetik;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sankarea
 */
public class Produk extends javax.swing.JFrame {
    
    DefaultTableModel TablePro;
    Koneksi conn;
    static String id;
    /**
     * Creates new form Produk
     */
    public Produk() {
        initComponents();
        conn = new Koneksi();
        loadTable();
    }
    
    public void loadTable(){
        Object[] field = {"Produk","Supplier", "Harga Kulak", "Harga", "Stok"};
        TablePro = new DefaultTableModel(null, field);
        TableProduk.setModel(TablePro);
        LTambahStok.setVisible(false);
        TTambahStok.setVisible(false);
        BAdd.setVisible(false);
        try{
            ResultSet tpro = conn.select("SELECT * FROM produk");
            while(tpro.next()){
                String produk = tpro.getString("PRODUK");
                String id_supplier = tpro.getString("ID_SUPPLIER");
                String harga_kulak = tpro.getString("HARGA_KULAK");
                String harga = tpro.getString("HARGA");
                String stok = tpro.getString("STOK");
                String[] data = {produk, id_supplier,harga_kulak,harga,stok};
                TablePro.addRow(data);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LABELPRODUK = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProduk = new javax.swing.JTable();
        BKembali = new javax.swing.JButton();
        BHapusProduk = new javax.swing.JButton();
        BUbahProduk = new javax.swing.JButton();
        BTambahProduk = new javax.swing.JButton();
        LTambahStok = new javax.swing.JLabel();
        TTambahStok = new javax.swing.JTextField();
        BAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LABELPRODUK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LABELPRODUK.setText("PRODUK");

        TableProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProduk);

        BKembali.setText("Kembali");
        BKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKembaliActionPerformed(evt);
            }
        });

        BHapusProduk.setText("Hapus");
        BHapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusProdukActionPerformed(evt);
            }
        });

        BUbahProduk.setText("Ubah");
        BUbahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUbahProdukActionPerformed(evt);
            }
        });

        BTambahProduk.setText("Tambah");
        BTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahProdukActionPerformed(evt);
            }
        });

        LTambahStok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LTambahStok.setText("Tambah Stok :");

        TTambahStok.setText("jTextField1");

        BAdd.setText("Add");
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(LABELPRODUK))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(BTambahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BUbahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BHapusProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LTambahStok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TTambahStok, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BAdd))
                            .addComponent(BKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LABELPRODUK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTambahStok)
                    .addComponent(TTambahStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAdd))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTambahProduk)
                    .addComponent(BUbahProduk)
                    .addComponent(BHapusProduk)
                    .addComponent(BKembali))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKembaliActionPerformed
        
        Menu mn = new Menu();
        mn.setVisible(true);
        mn.setLocationRelativeTo(null);
        mn.setDefaultCloseOperation(Login.DO_NOTHING_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BKembaliActionPerformed

    private void BHapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusProdukActionPerformed
        if(id != null){
        String[] where ={"ID_PRODUK", id};
        int tny = JOptionPane.showConfirmDialog(null, "Yakin menghapus data ini ?");
            if(tny == 0){
                boolean delete = conn.delete("produk", where);
                if(delete){
                    id = null;
                    loadTable();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Gagal menghapus !");
                }    
            }
        }
    }//GEN-LAST:event_BHapusProdukActionPerformed

    private void BUbahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahProdukActionPerformed
        // TODO add your handling code here:
        if(id != null){
            TambahProduk tproduk = new TambahProduk();
            tproduk.setVisible(true);
            tproduk.setLocationRelativeTo(null);
            tproduk.setDefaultCloseOperation(Login.DO_NOTHING_ON_CLOSE);
            this.dispose();
        }
        
        
//        String[][] data = {
//            {"ID_SUPPLIER"},
//            {"PRODUK"},
//            {"HARGA_KULAK"},
//            {"HARGA"},
//            {"STOK"}
//        };
//        String[] where  ={"PRODUK", id};
//        int tny = JOptionPane.showConfirmDialog(null, "Yakin mengubah data ini ?");
//        if(tny == 0){
//            boolean update = conn.update("produk", data, where);
//            if(update){
//                loadTable();
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "Gagal mengubah cek kembali!");
//            }   
//        }
       
    }//GEN-LAST:event_BUbahProdukActionPerformed

    private void BTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahProdukActionPerformed
        // TODO add your handling code here:
        Produk.id = null;
        TambahProduk tproduk = new TambahProduk();
        tproduk.setVisible(true);
        tproduk.setLocationRelativeTo(null);
        tproduk.setDefaultCloseOperation(Login.DO_NOTHING_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_BTambahProdukActionPerformed

    private void TableProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProdukMouseClicked
        // TODO add your handling code here:
        
        int row = TableProduk.getSelectedRow();
        String getData = (TableProduk.getModel().getValueAt(row, 0).toString());
        try{
            ResultSet tpro = conn.select("SELECT * FROM produk WHERE PRODUK = '"+getData+"'");
            while(tpro.next()){
                id = tpro.getString("ID_PRODUK");
//                TableProduk.setText(tpro.getString("NAMA_SUPPLIER"));
            }  
        }
        catch(Exception e){
            System.out.println(e);
            System.exit(0);
        }
        BTambahProduk.setVisible(true);
        BUbahProduk.setVisible(true);
        BHapusProduk.setVisible(true);
        BKembali.setVisible(true);
        LTambahStok.setVisible(true);
        TTambahStok.setText("");
        TTambahStok.setVisible(true);
        BAdd.setVisible(true);
    }//GEN-LAST:event_TableProdukMouseClicked

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddActionPerformed
        // TODO add your handling code here:
        try{
            ResultSet tpro = conn.select("SELECT STOK FROM produk WHERE ID_PRODUK = '"+id+"'");
            int stok = 0;
            if(tpro.next()){
                stok = tpro.getInt("STOK");
            }
            stok = stok + Integer.parseInt(TTambahStok.getText()); 
            String[][] data = {
                {"STOK", ""+stok}

            };
            String[] where = {"ID_PRODUK", id};
            boolean update = conn.update("produk", data, where);
            if (update) {
                loadTable();
            }
            else{
                JOptionPane.showConfirmDialog(null, "Gagal Menambah Stok");
            }  
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_BAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BHapusProduk;
    private javax.swing.JButton BKembali;
    private javax.swing.JButton BTambahProduk;
    private javax.swing.JButton BUbahProduk;
    private javax.swing.JLabel LABELPRODUK;
    private javax.swing.JLabel LTambahStok;
    private javax.swing.JTextField TTambahStok;
    private javax.swing.JTable TableProduk;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
