/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grosirkosmetik;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sankarea
 */
public class TambahProduk extends javax.swing.JFrame {
    
    Koneksi conn;
    String id;
    DefaultTableModel TableSupp;
    /**
     * Creates new form Produk
     */
    public TambahProduk() {
        initComponents();
        conn = new Koneksi();
        dapat_produk();
        loadTable();
    }
    
    public void loadTable(){
        Object[] field = {"ID Supplier","Nama Supplier"};
        TableSupp = new DefaultTableModel(null, field);
        TableSupplier.setModel(TableSupp);
        
        try{
            ResultSet tsup = conn.select("SELECT * FROM supplier");
            while(tsup.next()){
                String id_supp = tsup.getString("ID_SUPPLIER");
                String nama_supplier = tsup.getString("NAMA_SUPPLIER");
                String[] data = {id_supp, nama_supplier};
                TableSupp.addRow(data);
            }
        }
        catch(Exception e){
            
        }
    }

    public void tambah_produk(){
        String[][] data = {
            {"ID_SUPPLIER", LSupVal.getText()},
            {"PRODUK", TProduk.getText()},
            {"HARGA_KULAK",THargaKulak.getText()},
            {"HARGA",THarga.getText()},
            {"STOK",TStok.getText()}
        };
        try{
            boolean insert = conn.insert("produk", data);
            if(insert){
                Produk produk = new Produk();
                produk.setVisible(true);
                produk.setLocationRelativeTo(null);
                produk.setDefaultCloseOperation(Login.DO_NOTHING_ON_CLOSE);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal menambah cek kembali!");
            } 
        }
        catch(Exception e){
            //System.out.println(e);
        }
    }
    public void update_produk(){
        String[][] data = {
            {"ID_SUPPLIER", LSupVal.getText()},
            {"PRODUK", TProduk.getText()},
            {"HARGA_KULAK",THargaKulak.getText()},
            {"HARGA",THarga.getText()},
            {"STOK",TStok.getText()}
        };
        String[] where = {"ID_PRODUK", Produk.id};
        try{
            boolean update = conn.update("produk", data, where);
            if(update){
                Produk.id = null;
                Produk produk = new Produk();
                produk.setVisible(true);
                produk.setLocationRelativeTo(null);
                produk.setDefaultCloseOperation(Login.DO_NOTHING_ON_CLOSE);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal mengubah cek kembali!");
            } 
        }
        catch(Exception e){
            //System.out.println(e);
        }
    }
    public void dapat_produk(){
//        System.out.println(Produk.id);
        if(Produk.id != null){
            BTambah.setVisible(false);
            BBatal.setVisible(false);
            LStok.setVisible(false);
            TStok.setVisible(false);
            try{
                ResultSet tpro = conn.select("SELECT * FROM produk WHERE ID_PRODUK = "+Produk.id);
                if(tpro.next()){
                    LSupVal.setText(tpro.getString("ID_SUPPLIER"));
                    TProduk.setText(tpro.getString("PRODUK"));
                    THargaKulak.setText(tpro.getString("HARGA_KULAK"));
                    THarga.setText(tpro.getString("HARGA"));
                    TStok.setText(tpro.getString("STOK"));
                }
            }
            catch(Exception e){
                
            }
        }else{
            BUbah.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LSup = new javax.swing.JLabel();
        LProduk = new javax.swing.JLabel();
        LHargaKulak = new javax.swing.JLabel();
        LHarga = new javax.swing.JLabel();
        LStok = new javax.swing.JLabel();
        TProduk = new javax.swing.JTextField();
        THargaKulak = new javax.swing.JTextField();
        THarga = new javax.swing.JTextField();
        TStok = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BKembali = new javax.swing.JButton();
        BUbah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSupplier = new javax.swing.JTable();
        LSupVal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LSup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LSup.setText("Supplier");

        LProduk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LProduk.setText("Produk");

        LHargaKulak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LHargaKulak.setText("Harga Kulak");

        LHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LHarga.setText("Harga");

        LStok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LStok.setText("Stok");

        TProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TProdukActionPerformed(evt);
            }
        });

        THargaKulak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THargaKulakActionPerformed(evt);
            }
        });

        THarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THargaActionPerformed(evt);
            }
        });

        TStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TStokActionPerformed(evt);
            }
        });
        TStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TStokKeyPressed(evt);
            }
        });

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        BTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BTambahKeyPressed(evt);
            }
        });

        BBatal.setText("Batal");
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        BKembali.setText("Kembali");
        BKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKembaliActionPerformed(evt);
            }
        });

        BUbah.setText("Ubah");
        BUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUbahActionPerformed(evt);
            }
        });

        TableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TableSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSupplier);

        LSupVal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LProduk)
                            .addComponent(LHarga)
                            .addComponent(LStok)
                            .addComponent(LSup))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(LHargaKulak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(THargaKulak, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(THarga, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TStok, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LSupVal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTambah)
                            .addComponent(BUbah)
                            .addComponent(BBatal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BKembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LSup, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LSupVal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(TProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(THargaKulak, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LHargaKulak, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(THarga))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TStok, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LStok, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void TProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TProdukActionPerformed

    private void THargaKulakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THargaKulakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THargaKulakActionPerformed

    private void THargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THargaActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        //loadTable();
        LSupVal.setText("");
        TProduk.setText("");
        THargaKulak.setText("");
        THarga.setText("");
        TStok.setText("");
        BTambah.setVisible(true);
        BBatal.setVisible(true);
    }//GEN-LAST:event_BBatalActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here: 
        tambah_produk();
    }//GEN-LAST:event_BTambahActionPerformed

    private void BKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKembaliActionPerformed
        Produk.id = null;
        Produk produk = new Produk();
        produk.setVisible(true);
        produk.setLocationRelativeTo(null);
        produk.setDefaultCloseOperation(Login.DO_NOTHING_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BKembaliActionPerformed

    private void BTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTambahKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            tambah_produk();
        }
    }//GEN-LAST:event_BTambahKeyPressed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        // TODO add your handling code here:
        update_produk();
    }//GEN-LAST:event_BUbahActionPerformed

    private void TStokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TStokKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            tambah_produk();
        }
    }//GEN-LAST:event_TStokKeyPressed

    private void TStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TStokActionPerformed

    private void TableSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSupplierMouseClicked
        int row = TableSupplier.getSelectedRow();
        String getData = (TableSupplier.getModel().getValueAt(row, 0).toString());
        try{
            ResultSet tsup = conn.select("SELECT * FROM supplier WHERE ID_SUPPLIER = "+getData);
            while(tsup.next()){
                LSupVal.setText(tsup.getString("ID_SUPPLIER"));
            }  
        }
        catch(Exception e){
            System.out.println(e);
            System.exit(0);
        }
    }//GEN-LAST:event_TableSupplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BKembali;
    private javax.swing.JButton BTambah;
    private javax.swing.JButton BUbah;
    private javax.swing.JLabel LHarga;
    private javax.swing.JLabel LHargaKulak;
    private javax.swing.JLabel LProduk;
    private javax.swing.JLabel LStok;
    private javax.swing.JLabel LSup;
    private javax.swing.JLabel LSupVal;
    private javax.swing.JTextField THarga;
    private javax.swing.JTextField THargaKulak;
    private javax.swing.JTextField TProduk;
    private javax.swing.JTextField TStok;
    private javax.swing.JTable TableSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
